# Generated by Django 5.1.3 on 2024-12-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usermetadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermetadata',
            old_name='email_verifield',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='private',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
