# Generated by Django 5.1.3 on 2024-12-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=48, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
