# Generated by Django 5.1.3 on 2024-12-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_country_alter_usermetadata_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='description',
            field=models.CharField(default='default text', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='profile_img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
