# Generated by Django 5.1.3 on 2024-12-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_code_emailauthcode_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailauthcode',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['created_at']},
        ),
    ]
