# Generated by Django 5.1.3 on 2024-12-20 21:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_emailauthcode_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailAuthCode',
            new_name='EmailAuthToken',
        ),
        migrations.RenameModel(
            old_name='PasswordResetCode',
            new_name='PasswordResetToken',
        ),
    ]
