# Generated by Django 5.1.3 on 2025-01-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_post_options_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date']},
        ),
    ]
