# Generated by Django 5.1.3 on 2025-01-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date', 'author']},
        ),
    ]
