# Generated by Django 5.1.1 on 2025-01-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_post_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtags',
            new_name='Hashtag',
        ),
        migrations.RenameModel(
            old_name='PostHashtags',
            new_name='PostHashtag',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_posts', to='api.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_posts', to='api.post')),
            ],
        ),
    ]
