# Generated by Django 5.1.3 on 2025-01-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_hashtags_hashtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
