# Generated by Django 5.1.3 on 2025-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_hashtag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='mentions',
            field=models.IntegerField(default=1),
        ),
    ]
