# Generated by Django 5.1.3 on 2025-01-26 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_hashtag_mentions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reposts',
            new_name='Dislike',
        ),
        migrations.RenameModel(
            old_name='Saves',
            new_name='Like',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Repost',
        ),
        migrations.RenameModel(
            old_name='Dislikes',
            new_name='Save',
        ),
        migrations.RemoveConstraint(
            model_name='dislike',
            name='post_id__user_id-reposts',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='post_id__user_id-saves',
        ),
        migrations.RemoveConstraint(
            model_name='repost',
            name='post_id__user_id-likes',
        ),
        migrations.RemoveConstraint(
            model_name='save',
            name='post_id__user_id-dislikes',
        ),
        migrations.AddConstraint(
            model_name='dislike',
            constraint=models.UniqueConstraint(fields=('post_id', 'user_id'), name='post_id__user_id-dislike'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post_id', 'user_id'), name='post_id__user_id-like'),
        ),
        migrations.AddConstraint(
            model_name='repost',
            constraint=models.UniqueConstraint(fields=('post_id', 'user_id'), name='post_id__user_id-repost'),
        ),
        migrations.AddConstraint(
            model_name='save',
            constraint=models.UniqueConstraint(fields=('post_id', 'user_id'), name='post_id__user_id-save'),
        ),
    ]
