# Generated by Django 5.1.3 on 2025-01-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_reposts_dislike_rename_saves_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_post',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
